"""
Django settings for userdemo project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os 
from   pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2qk-+39^g6r6u!5xyxj4)_%gir=2ey_i5$s(d#-88#exrr@!0&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ##
    'social_django',
    'pf_core.apps.PfCoreConfig',
]

## Tuning
AUTH_USER_MODEL = 'pf_core.PfUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ## My add-ons
    'pf_core.middleware.PfCoreMiddleware',
]

ROOT_URLCONF = 'userdemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'userdemo/templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                ##
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                ##
                'pf_core.context_processors.pf_core',
            ],
        },
    },
]

WSGI_APPLICATION = 'userdemo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

_pswdval_stub = 'django.contrib.auth.password_validation'  # more readable

AUTH_PASSWORD_VALIDATORS = [
    {  'NAME': _pswdval_stub + '.UserAttributeSimilarityValidator',  },
    {  'NAME': _pswdval_stub + '.MinimumLengthValidator',            },
    {  'NAME': _pswdval_stub + '.CommonPasswordValidator',           },
    {  'NAME': _pswdval_stub + '.NumericPasswordValidator',          },
]

##

SOCIAL_AUTH_URL_NAMESPACE = 'social'


SOCIAL_AUTH_MICROSOFT_GRAPH_KEY = os.environ.get("SOCIAL_AUTH_MICROSOFT_GRAPH_KEY", "NA")
SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET = os.environ.get("SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET", "NA")
SOCIAL_AUTH_MICROSOFT_GRAPH_LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = SOCIAL_AUTH_MICROSOFT_GRAPH_KEY
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET
SOCIAL_AUTH_AZUREAD_OAUTH2_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE = 'https://graph.microsoft.com/'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.azuread_tenant.AzureADOAuth2',
    'social_core.backends.microsoft.MicrosoftOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    # 'social_core.pipeline.mail.mail_validation',
    # 'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    ## # 'social_core.pipeline.debug.debug',
    # 'pf_core.pipeline.debug',
)

SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    'social_core.pipeline.disconnect.allowed_to_disconnect',
    'social_core.pipeline.disconnect.get_entries',
    'social_core.pipeline.disconnect.revoke_tokens',
    'social_core.pipeline.disconnect.disconnect',
)


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "userdemo/static",
]

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##----------------------------------------------------------------------------
## Logging
## https://docs.djangoproject.com/en/4.0/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            # Removed "{thread:d}" as it was really too long and not that useful
            'format': '{asctime} {process:5d} {levelname:^7s} '
                      '{name}:{module}:{funcName}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {   ## adapted to Docker logs
            'format': '{asctime} {levelname:^7s} {funcName}: {message}',
                      # '{name}:{module}:{funcName}: {message}',
             'style': '{',
        },
    },
    'filters': {
        # 'special': {
        #     '()': 'project.logging.SpecialFilter',
        #     'foo': 'bar',
        # },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG', ## 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            # 'formatter': 'simple'
            'formatter': 'verbose'
        },
        'prod': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.StreamHandler',
            # 'formatter': 'simple'
            'formatter': 'detailed'
        },
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': '/path/to/django/debug.log',
        # },
        # 'mail_admins': {
        #     'level': 'ERROR',
        #     'class': 'django.utils.log.AdminEmailHandler',
        #     'filters': ['require_debug_false']
        # }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'prod'],
            'propagate': True,
        },
        # 'django.request': {
        #     'handlers': ['mail_admins'],
        #     'level': 'ERROR',
        #     'propagate': False,
        # },
        # 'myproject.custom': {
        #     'handlers': ['console', 'mail_admins'],
        #     'level': 'INFO',
        #     'filters': ['special']
        # },
        'userdemo':    { 'handlers': ['console', 'prod'], 'level': 'DEBUG' },
        'pf_core':     { 'handlers': ['console', 'prod'], 'level': 'DEBUG' },

        'requests':          { 'handlers': ['console'], 'level': 'WARNING' },
        'requests_oauthlib': { 'handlers': ['console'], 'level': 'WARNING' },
        'urllib3':           { 'handlers': ['console'], 'level': 'WARNING' },
    }
}
